version: '3.4'

# volumes:
#   template:

services:
  main:
    container_name: template

    # image: ubuntu:jammy-20221101
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ..:/home/user/project
      - type: bind
        source: ~/.ssh
        target: /home/user/.ssh
        read_only: true
    # ports:
    #   - "8881:8888" #set by yourself
    cap_add: 
      - SYS_PTRACE
    privileged: true
    security_opt: 
      - seccomp:unconfined
    stdin_open: true
    tty: true
    working_dir: /home/user/project
